include:
  - board: corneish_zen_left/zmk
    # snippet: zmk-usb-logging  # uncomment to enable logging
  - board: corneish_zen_right/zmk
  - board: corneish_zen_left/zmk
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=n
    artifact-name: corneish_zen_v2_left_with_studio
  # - board: corneish_zen_left@1.0.0//zmk
  # - board: corneish_zen_right@1.0.0//zmk
